using UnityEngine;
using FMODUnity;
using FMOD.Studio;
using UnityEngine.UIElements;

public class SoundController : MonoBehaviour
{
    private EventInstance musicEvent;
    
    void Start()
    {
        // FMODì—ì„œ ë…¸ë˜ ì´ë²¤íŠ¸ ìƒì„±
        musicEvent = RuntimeManager.CreateInstance("event:/Music_Full");
        musicEvent.start();
        
        
        
    }

    void Update()
    {
        Slider slider = GetComponent<Slider>();
        SetMusicVolume(slider.value);
    }

    // ğŸ”Š ë³¼ë¥¨ ì¡°ì ˆ í•¨ìˆ˜
    private void SetMusicVolume(float volume)
    {
        musicEvent.setVolume(volume);
    }
}